currencies = {
"United States – US Dollar (USD)": "USD",
"India – Indian Rupee (INR)": "INR",
"United Kingdom – Pound Sterling (GBP)": "GBP",
"European Union – Euro (EUR)": "EUR",
"Japan – Japanese Yen (JPY)": "JPY",
"China – Chinese Yuan (CNY)": "CNY",
"Australia – Australian Dollar (AUD)": "AUD",
"Canada – Canadian Dollar (CAD)": "CAD",
"Switzerland – Swiss Franc (CHF)": "CHF",
"Singapore – Singapore Dollar (SGD)": "SGD",
"United Arab Emirates – UAE Dirham (AED)": "AED",
"Afghanistan – Afghan Afghani (AFN)": "AFN",
"Albania – Albanian Lek (ALL)": "ALL",
"Armenia – Armenian Dram (AMD)": "AMD",
"Argentina – Argentine Peso (ARS)": "ARS",
"Austria – Euro (EUR)": "EUR",
"Bangladesh – Bangladeshi Taka (BDT)": "BDT",
"Belgium – Euro (EUR)": "EUR",
"Brazil – Brazilian Real (BRL)": "BRL",
"Bulgaria – Bulgarian Lev (BGN)": "BGN",
"Chile – Chilean Peso (CLP)": "CLP",
"Colombia – Colombian Peso (COP)": "COP",
"Czech Republic – Czech Koruna (CZK)": "CZK",
"Denmark – Danish Krone (DKK)": "DKK",
"Egypt – Egyptian Pound (EGP)": "EGP",
"Hong Kong – Hong Kong Dollar (HKD)": "HKD",
"Hungary – Hungarian Forint (HUF)": "HUF",
"Indonesia – Indonesian Rupiah (IDR)": "IDR",
"Israel – Israeli New Shekel (ILS)": "ILS",
"Malaysia – Malaysian Ringgit (MYR)": "MYR",
"Mexico – Mexican Peso (MXN)": "MXN",
"New Zealand – New Zealand Dollar (NZD)": "NZD",
"Norway – Norwegian Krone (NOK)": "NOK",
"Nepal – Nepalese Rupee (NPR)": "NPR",
"Pakistan – Pakistani Rupee (PKR)": "PKR",
"Philippines – Philippine Peso (PHP)": "PHP",
"Poland – Polish Zloty (PLN)": "PLN",
"Qatar – Qatari Riyal (QAR)": "QAR",
"Romania – Romanian Leu (RON)": "RON",
"Russia – Russian Ruble (RUB)": "RUB",
"Saudi Arabia – Saudi Riyal (SAR)": "SAR",
"South Africa – South African Rand (ZAR)": "ZAR",
"South Korea – South Korean Won (KRW)": "KRW",
"Sri Lanka – Sri Lankan Rupee (LKR)": "LKR",
"Sweden – Swedish Krona (SEK)": "SEK",
"Thailand – Thai Baht (THB)": "THB",
"Turkey – Turkish Lira (TRY)": "TRY",
"Ukraine – Ukrainian Hryvnia (UAH)": "UAH",
"Vietnam – Vietnamese Dong (VND)": "VND",
"Nigeria – Nigerian Naira (NGN)": "NGN",
"Kenya – Kenyan Shilling (KES)": "KES",
"Ghana – Ghanaian Cedi (GHS)": "GHS",
"Peru – Peruvian Sol (PEN)": "PEN",
"Argentina – Argentine Peso (ARS)": "ARS",
"Bolivia – Bolivian Boliviano (BOB)": "BOB",
"Costa Rica – Costa Rican Colon (CRC)": "CRC",
"Dominican Republic – Dominican Peso (DOP)": "DOP",
"El Salvador – US Dollar (USD)": "USD",
"Guatemala – Guatemalan Quetzal (GTQ)": "GTQ",
"Honduras – Honduran Lempira (HNL)": "HNL",
"Jamaica – Jamaican Dollar (JMD)": "JMD",
"Panama – Balboa (PAB)": "PAB",
"Paraguay – Guarani (PYG)": "PYG",
"Uruguay – Uruguayan Peso (UYU)": "UYU",
"Uzbekistan – Uzbekistani Som (UZS)": "UZS",
"Kazakhstan – Kazakhstani Tenge (KZT)": "KZT",
"Georgia – Georgian Lari (GEL)": "GEL",
"Armenia – Armenian Dram (AMD)": "AMD",
"Iceland – Icelandic Krona (ISK)": "ISK",
"Serbia – Serbian Dinar (RSD)": "RSD",
"Croatia – Euro (EUR)": "EUR",
"Slovakia – Euro (EUR)": "EUR",
"Slovenia – Euro (EUR)": "EUR",
"Luxembourg – Euro (EUR)": "EUR",
"Malta – Euro (EUR)": "EUR",
"Cyprus – Euro (EUR)": "EUR"
}